server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  application:
    name: paylink
  datasource:
    url: jdbc:mysql://localhost:3306/paylinkdb?createDatabaseIfNotExist=true
    username: root
    password: user@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: vanashri7795@gmail.com
    password: vanuamardeshpande

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: mysecurekeythatis32charslong123456
